### ISSUE TITLE
jshint could be optional

### ISSUE THREAD

**Issue by marapper** [thadclay/prepush-hook#2]
It's good module but every time I execute npm install it creates .jshintignore and .jshintrc. It would be better if module suggest it not to force it (for ex. I use eslint).

**Comment by bebraw** [comment]
:+1: This change would be great.

**Comment by chadxz** [comment]
Would also be great if the jshint peerDependency could be removed for the same reason. We use eslint in our project and have no need for jshint, and it's just one extra thing to install in development :(

**Comment by sturdynut** [comment]
I forked this and removed the jshint dependency:  https://github.com/sturdynut/prepush-hook

**Comment by bebraw** [comment]
@sturdynut Any chance for a npm release under a different name perhaps?

**Comment by sturdynut** [comment]
@bebraw - See here:  https://github.com/sturdynut/git-prepush-hook

`npm install git-prepush-hook`

**Comment by bebraw** [comment]
@sturdynut Got it. Thanks.
